trigger:
  - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '10.0.101'

  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '20.x'

  - script: |
      npm install -g yarn@1.22.19
    displayName: 'Install Yarn'

  - script: |
      ./build.sh --all
    displayName: 'Build Bookdarr (Linux)'
