// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'authSuccess': string;
  'deleteButton': string;
  'hardcoverAuthButtons': string;
  'hardcoverAuthRow': string;
  'hideMetadataProfile': string;
  'labelIcon': string;
  'message': string;
}
export const cssExports: CssExports;
export default cssExports;
