#!/usr/bin/with-contenv bash
# shellcheck shell=bash

cd /app/readarr/bin

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 \
            s6-setuidgid abc /app/readarr/bin/Readarr -nobrowser -data=/config
else
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 \
            /app/readarr/bin/Readarr -nobrowser -data=/config
fi
